// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerSpinner.Functions.Data;

#nullable disable

namespace ServerSpinner.Functions.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417155537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerSpinner.Core.Entities.SpinnerState", b =>
                {
                    b.Property<Guid>("StreamerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStreamer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayedSongIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StreamerId");

                    b.ToTable("SpinnerStates");
                });

            modelBuilder.Entity("ServerSpinner.Core.Entities.Streamer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId")
                        .IsUnique();

                    b.ToTable("Streamers");
                });

            modelBuilder.Entity("ServerSpinner.Core.Entities.StreamerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoPlay")
                        .HasColumnType("boolean");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackgroundMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorButtonBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorButtonText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorPlayedItemBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorPlayedListBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorPointer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorResizeHandleBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorResizeHandleHoverBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorStatusBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorToggleBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DebugMode")
                        .HasColumnType("boolean");

                    b.Property<string>("DefaultStreamerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ExcludePlayedSongs")
                        .HasColumnType("boolean");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FontSize")
                        .HasColumnType("integer");

                    b.Property<bool>("HideChangeOptionWhenDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayHistoryPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayedListFontFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayedListFontSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayedListMaxLines")
                        .HasColumnType("integer");

                    b.Property<string>("PlayedListPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SongListFields")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<string>("StreamerSonglistUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WheelColors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("StreamerSettings");
                });

            modelBuilder.Entity("ServerSpinner.Core.Entities.StreamerSettings", b =>
                {
                    b.HasOne("ServerSpinner.Core.Entities.Streamer", "Streamer")
                        .WithOne("Settings")
                        .HasForeignKey("ServerSpinner.Core.Entities.StreamerSettings", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("ServerSpinner.Core.Entities.Streamer", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
